apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slab-ai-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: slab-ai-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: slab-ai-backend
            port:
              number: 80
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: slab-ai-backend
            port:
              number: 80
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: slab-ai-backend
            port:
              number: 80
