FROM node:18-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN addgroup -g 1001 -S nginx
RUN adduser -S slab-ai -u 1001

USER slab-ai

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
